### ISSUE TITLE
Multiple request issue

### ISSUE THREAD

**Issue by cdebast** [NoNews/NoPermission#4]
When multiple permissions are requested at the same time, the 'onSuccess' listener is called ONCE only if ALL permissions are granted. I was expecting to have a call to 'onSuccess' for each granted permission, and 'onDenied' for each denied.

bug is in "onRequestPermissionsResult"

**Comment by NoNews** [comment]
Hi @cdebast, thank you for this issue and sorry for long answer.

The concept of the library assumes that the `onSuccess();` will be called only if all the requested  permissions are granted.

It is for this reason that we use ordinary `Runnable` without parameters, instead custom callbacks.
